device: 'cuda:5'

stages:
  align: true
  gaincomp: false
  graphcut: false
  blending: false

save_transforms: false
load_transforms: true

dirs:
  datasets_dir: "/home/g.nikolaev/data/tiles"
  matches_dir: "/home/g.nikolaev/data/matches"
  transforms_dir: "/home/g.nikolaev/data/transforms"
  panoramas_dir: "/home/g.nikolaev/data/panoramas"

graphcut:
  coarse_scale: 16
  fine_scale: 4
  lane_width: 200

blending:
  levels: 7
