device: "cuda:5"

stages:
  align: true
  gaincomp: true
  graphcut: true
  blending: false

save_transforms: true
load_transforms: false

dirs:
  datasets_dir: "/home/g.nikolaev/data/tiles"
  inliers_dir: "/home/g.nikolaev/data/inliers"
  transforms_dir: "/home/g.nikolaev/data/transforms"
  panoramas_dir: "/home/g.nikolaev/data/panoramas_blended"

graphcut:
  coarse_scale: 16
  fine_scale: 4
  lane_width: 200

blending:
  levels: 7